// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4onDGDHYWxrW6PrtkeNUcE1WRi85UZjc',
    appId: '1:252992780153:web:4336f71d40c8ff4f44e1a8',
    messagingSenderId: '252992780153',
    projectId: 'ecommerce-app-a3a1f',
    authDomain: 'ecommerce-app-a3a1f.firebaseapp.com',
    storageBucket: 'ecommerce-app-a3a1f.appspot.com',
    measurementId: 'G-CJ6XFXX6HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfnZYeMsHiw7tnvssoq8T4iZoiecTlQz8',
    appId: '1:252992780153:android:df47d7698bc33d4944e1a8',
    messagingSenderId: '252992780153',
    projectId: 'ecommerce-app-a3a1f',
    storageBucket: 'ecommerce-app-a3a1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBenyQsl0IyKqbOghuy2Vo3JrukILdqAM8',
    appId: '1:252992780153:ios:f4e3445208af935544e1a8',
    messagingSenderId: '252992780153',
    projectId: 'ecommerce-app-a3a1f',
    storageBucket: 'ecommerce-app-a3a1f.appspot.com',
    iosClientId: '252992780153-v8plg13qnbqfn34u5udjevnc50bbmhtl.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBenyQsl0IyKqbOghuy2Vo3JrukILdqAM8',
    appId: '1:252992780153:ios:f4e3445208af935544e1a8',
    messagingSenderId: '252992780153',
    projectId: 'ecommerce-app-a3a1f',
    storageBucket: 'ecommerce-app-a3a1f.appspot.com',
    iosClientId: '252992780153-v8plg13qnbqfn34u5udjevnc50bbmhtl.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
